/* driver/myconf.h.  Generated by configure.  */
/* driver/myconf.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <iodbcinst.h> header file. */
/* #undef HAVE_IODBCINST_H */

/* Define to 1 if you have the <isqlext.h> header file. */
/* #undef HAVE_ISQLEXT_H */

/* Define to 1 if you have the <isqltypes.h> header file. */
/* #undef HAVE_ISQLTYPES_H */

/* Define to 1 if you have the <isql.h> header file. */
/* #undef HAVE_ISQL_H */

/* Define to 1 if you have the `z' library (-lz). */
#define HAVE_LIBZ 1

/* Define to 1 if you have the `localtime_r' function. */
#define HAVE_LOCALTIME_R 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <odbcinst.h> header file. */
#define HAVE_ODBCINST_H 1

/* Define to 1 if you have the <sqlext.h> header file. */
#define HAVE_SQLEXT_H 1

/* Define if SQLGetPrivateProfileString is defined */
#define HAVE_SQLGETPRIVATEPROFILESTRING 1

/* Define to 1 if you have the <sqltypes.h> header file. */
#define HAVE_SQLTYPES_H 1

/* Define to 1 if you have the <sql.h> header file. */
#define HAVE_SQL_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strndup' function. */
#define HAVE_STRNDUP 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "mysql-connector-odbc"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define if SQLCHAR is undefined */
/* #undef SQLCHAR */

/* Define if SQLHDBC is undefined */
/* #undef SQLHDBC */

/* Define if SQLHENV is undefined */
/* #undef SQLHENV */

/* Define if SQLHSTMT is undefined */
/* #undef SQLHSTMT */

/* Define if SQLHWND is undefined */
/* #undef SQLHWND */

/* Define if SQLINTEGER is undefined */
/* #undef SQLINTEGER */

/* Define if SQLPOINTER is undefined */
/* #undef SQLPOINTER */

/* Define if SQLRETURN is undefined */
/* #undef SQLRETURN */

/* Define if SQLSMALLINT is undefined */
/* #undef SQLSMALLINT */

/* Define if SQLUINTEGER is undefined */
/* #undef SQLUINTEGER */

/* Define if SQLUSMALLINT is undefined */
/* #undef SQLUSMALLINT */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define path to system ODBC.INI file */
/* #undef SYSTEM_ODBC_INI */

/* Define if compiler defines C99 __func__ macro */
#define USE_C99_FUNC_MACRO 1

/* Define if compiler defines __FUNCTION__ */
#define USE_GNU_FUNC_MACRO 1

/* use iODBC */
/* #undef USE_IODBC */

/* Define if SQLColAttribute() last arg is compatible with SQLLEN* */
#define USE_SQLCOLATTRIBUTE_SQLLEN_PTR 1

/* Define if SQLColAttribute() last arg is compatible with SQLPOINTER */
/* #undef USE_SQLCOLATTRIBUTE_SQLPOINTER */

/* Define if SQLParamOptions() 2nd and 3rd arg is compatible with SQLUINTEGER
   */
/* #undef USE_SQLPARAMOPTIONS_SQLUINTEGER_PTR */

/* Define if SQLParamOptions() 2nd and 3rd arg is compatible with SQLULEN */
#define USE_SQLPARAMOPTIONS_SQLULEN_PTR 1

/* use unixODBC */
#define USE_UNIXODBC 1

/* Version number of package */
#define VERSION "3.51.25"

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define if we are using unix build environment */
#define _UNIX_ 1
